# Generated by Django 3.2.13 on 2022-05-10 18:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20220508_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='birth_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Birth date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='surname',
            field=models.CharField(default='', max_length=255, unique=True, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.CharField(max_length=512, verbose_name='Description'),
        ),
        migrations.AlterUniqueTogether(
            name='author',
            unique_together={('name', 'surname')},
        ),
    ]
